version: "3.8"
services:
  react-app:
    #    stdin_open: true
    #    tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=burger-prod
    ports:
      - "8080:80"
#    env_file:
#      - ./.env

